<div class="faq-content">
    <h1><?php echo $this->getFaqTitle();?></h1>
    <div class="details">
        <div class="created-by">
            <?php echo __('Created by'); ?> Cuong Ngo <?php echo __('on'); ?> <?php echo $this->getFaqCreated(); ?>. <?php echo __('Published in'); ?> FAQs Category. <?php echo $this->getFaqViewed(); ?> Viewed.
        </div>
        <br/>
        <?php echo $this->getFaqContent(); ?>
    </div>
</div>


