<div class="faq-content">
    <h1><?php echo $this->getFaqTitle();?></h1>
    <div class="details">
        <div class="created-by">
            <?php echo ($this->getFullName())? __('Created by').' '.$this->getFullName().' '.__('on').' '.$this->getFaqCreated().', ' : ''; ?> <?php echo ($this->getFaqCategoryTitle())? __('published in').' '.$this->getFaqCategoryTitle().',' : ''; ?> <?php echo $this->getFaqViewed(); ?> <?php echo __('Viewed'); ?>.
        </div>
        <div class="content"><?php echo $this->getFaqContent(); ?></div>
        <div class="feedback" id="feedback">
            <div class="hidden" id="BASE_URL"><?php echo $block->getUrl('faq/question/ajax'); ?></div>
            <div class="hidden" id="FAQ_ID"><?php echo $this->getFaqId(); ?></div>
            <div class="hidden" id="message"><?php echo __('Glad to hear it — Thanks for the feedback'); ?></div>
            <span><?php echo __('Was this article helpful?'); ?></span>
            <button class="btn" id="btn-like"><?php echo __('Yes'); ?></button>
            <button class="btn" id="btn-dislike"><?php echo __('No'); ?></button>
        </div>
    </div>
    <?php if ($this->getRelatedQuestion()): ?>
        <div class="related-question">
            <h2><?php echo __('Related Questions');?></h2>
            <ol class="items">
                <?php foreach($this->getRelatedQuestion() as $faq): ?>
                    <li class="item">
                        <a href="<?php echo $block->getUrl($this->getFaqPath().'/'.$faq['identifier'].$this->getFaqDotHtml()); ?>"><?php echo $faq['title']; ?></a>
                    </li>
                <?php endforeach; ?>
            </ol>
        </div>
    <?php endif; ?>
</div>


